/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      sm: '375px',
      md: '768px', 
      lg: '1440px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        md: '2rem',
        lg: '2rem',
      },
      screens: {
        sm: '100%',
        md: '100%',
        lg: '1280px',
      },
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: '#171717',
          hover: '#0a0a0a',
          invert: '#ffffff',
        },
        secondary: '#525252',
        tertiary: '#737373',
        brand: '#4338ca',
        disabled: '#a3a3a3',
        error: {
          DEFAULT: '#dc2626',
          emphasize: '#991b1b',
        },
        success: '#15803d',
        warning: '#a16207',
        background: {
          primary: '#ffffff',
          'primary-inverted': '#0a0a0a',
          'primary-hover': '#fafafa',
          secondary: '#e5e7eb',
          'secondary-hover': '#d1d5db',
          tertiary: '#fafafa',
          disabled: '#f5f5f5',
          'disabled-emphasize': '#f3f4f6',
          'brand-primary': '#4338ca',
          'brand-primary-emphasize': '#3730a3',
          error: '#dc2626',
          'error-emphasize': '#b91c1c',
          'error-subtle': '#fef2f2',
          'success-subtle': '#f0fdf4',
          'brand-subtle': '#eef2ff',
          'neutral-subtle': '#f9fafb',
          'warning-subtle': '#fffbeb',
        },
        border: {
          primary: '#e5e5e5',
          secondary: '#9ca3af',
          success: '#bbf7d0',
          'brand-solid': '#4f46e5',
          'brand-subtle': '#c7d2fe',
          'error-subtle': '#fecaca',
          'warning-subtle': '#fde68a',
        },
        icon: {
          emphasize: '#404040',
          primary: '#a3a3a3',
          'primary-hover': '#737373',
          brand: '#6366f1',
          'brand-background': '#eef2ff',
          success: '#15803d',
          error: '#dc2626',
          warning: '#facc15',
        },
        form: {
          'text-title': '#404040',
          'text-placeholder': '#737373',
          'text-hint': '#737373',
          'text-filled': '#171717',
          'text-disabled': '#a3a3a3',
          'text-error': '#dc2626',
          background: '#fafafa',
          border: '#e5e5e5',
        },
      },
      gridTemplateColumns: {
        mobile: 'repeat(4, 1fr)',
        tablet: 'repeat(6, 1fr)',
        desktop: 'repeat(12, 1fr)',
      },
      gap: {
        grid: '2rem',
        'grid-mobile': '1rem',
      },
    },
  },
  plugins: [],
};